version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 25
    ignore:
      - dependency-name: "Npgsql"
      - dependency-name: "MediaInfoDotNet"
